services:
  - type: web
    name: utr-bot
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: "YOUR_BOT_TOKEN_HERE"
